### PR TITLE
#134 - Changed tables to card sets

### PR DESCRIPTION
**Pull request by RahulR100**
Collapsed:
image

Some expanded:
image

### CODE REVIEW

**Comment by jamescd18** [comment]
Can we get some screenshots here of collapsed and expanded?

**Comment by RahulR100** [comment]
Collapsed:
image

Some expanded:
image

**Review by kevinyu328 — CHANGES_REQUESTED** [review]
Looks good! But can you add some comments in the `buildTableHTML` function and reformat it a little so that it's more readable. Thanks!

**Review by kevinyu328 — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
